### ISSUE TITLE
领取耐力问题

### ISSUE THREAD

**Issue by aurorax-neo** [dongyazhuo/imaotai#15]
领取耐力不可用，预约后 领取耐力返回{"code":40001,"message":"任务未完成，无法领取奖励","data":null,"error":null}，还要手动领取。虽然手动领取耐力后也是这个返回结果，可能是接口逻辑问题。
但是 领取耐力功能希望修复一下

**Comment by DavidNi666** [comment]
耐力是可以领取的，response code : 200, response body : {"code":200,"message":null,"data":{"continueReserveRate":null,"awardRule":[{"goodId":20001,"goodName":"耐力","goodCode":null,"goodType":null,"goodUrl":null,"count":10}]},"error":null}

有可能你已经运行领取过了。 


@yazhuo-wyze  请问是否可以搞一下领取小茅运，非常感谢！！！

**Comment by yazhuo-wyze** [comment]
> 

耐力都是一个网友提供的PR。我后来没太研究这个了。

**Comment by GoToBoy** [comment]
可能需要加一个延迟，申购完成，服务器还没响应过来，会提示任务未完成

**Comment by JohnyWu** [comment]
> 领取耐力不可用，预约后 领取耐力返回{"code":40001,"message":"任务未完成，无法领取奖励","data":null,"error":null}，还要手动领取。虽然手动领取耐力后也是这个返回结果，可能是接口逻辑问题。
> 但是 领取耐力功能希望修复一下

我也是遇到一样的问题 @yazhuo-wyze

**Comment by yazhuo-wyze** [comment]
在9-10点把任务跑多次试试。

**Comment by yirenyishi** [comment]
我是把领取耐力另外写了个定时任务，5分钟后领取是没有问题的

**Comment by yazhuo-wyze** [comment]
> 我是把领取耐力另外写了个定时任务，5分钟后领取是没有问题的

具体怎么做呢？还有一份python代码？

**Comment by JohnyWu** [comment]
> 我是把领取耐力另外写了个定时任务，5分钟后领取是没有问题的

可否分享下？谢谢

**Comment by Aurorax-own** [comment]
> 

多执行 两次就好了
